
[build]
  # install & build your CRA app
  command   = "npm run build"
  publish   = "build"

# Ensure all paths serve index.html (for clientâ€side routing)
[[redirects]]
  from    = "/*"
  to      = "/index.html"
  status  = 200
